//! The GBNF grammar, built out of the shape it has to agree with.
//!
//! `vault/02-Arquitectura/Gamas-de-Modelo.md` decrees that every inference runs
//! with grammar-constrained decoding, and states what that buys:
//!
//! > A malformed contract is impossible on all four tiers. What changes between
//! > tiers is not safety, it is accuracy at reading intent.
//!
//! That sentence is only true if the grammar and [`crate::proposal`] agree. Two
//! places holding the same judgement drift, and this pair drifts in the worst
//! direction available: a grammar that permits a spelling the parser rejects
//! makes every single inference fail, and a model that fails on everything looks
//! exactly like a model that is bad at the task. So the operation names come
//! from [`ProposedOperation::name`], and the module-id character classes are
//! cross-checked against the scanner in the tests below rather than being a
//! second opinion about what an id is.
//!
//! ## What the grammar refuses, which is more than the parser does
//!
//! - **An operation outside the decreed scope is unsayable**, not merely
//!   unused. `remove_module` cannot be emitted, so it cannot be parsed, so it
//!   cannot be a bug later.
//! - **A target that is not shaped like a module id cannot be emitted.** The
//!   parser accepts any string in `targets` and lets attribution refuse it; the
//!   grammar declines to spend tokens on it in the first place.
//! - **Provenance fields cannot be emitted.** `deny_unknown_fields` already
//!   rejects them — see `proposal.rs` — and this stops them being generated.
//!   Both halves are wanted: the grammar is the tier's guarantee, and the parser
//!   is the guarantee for every route that does not go through llama.cpp.
//!
//! ## The empty target list, which is how abstention is said
//!
//! The first version of this grammar required at least one module id, and that
//! made **abstention inexpressible**. `Gamas-de-Modelo.md` calls abstention the
//! measurement that matters most — "an agent that is wrong by asking for
//! clarification costs a second, and one that invents with confidence costs the
//! trusted path" — and a grammar with no way to say *I did not find one* forces
//! the confident invention on every ambiguous sentence. The model would not
//! have been bad at abstaining; it would have been unable to.
//!
//! It was found by writing the bench that scores abstention, before either had
//! ever run. An empty list lands on `AgentError::NothingToDo`, which is the
//! sentence the agent already had for this and had no way to reach from here.
//!
//! ## What it does not do
//!
//! It does not bound length. A grammar describes a language, and this language
//! contains arbitrarily long module ids. The bound on a runaway is
//! `MAX_RESPONSE_BYTES` in `proposal.rs` and the token cap handed to llama.cpp.

use crate::proposal::ProposedOperation;

/// What a module-id segment may start with, as a GBNF character class body.
///
/// Kept as a constant rather than inlined so the test below can compare it
/// against `router::looks_like_module_id`, which is the authority.
const SEGMENT_FIRST: &str = "a-z";

/// What the rest of a module-id segment may contain.
const SEGMENT_REST: &str = "a-z0-9_-";

/// The characters a semver range is made of.
///
/// Deliberately loose: `semver` is what decides whether a range is a range, and
/// a grammar that tried to encode the full syntax would be a second, worse
/// implementation of it. This only keeps prose out.
const RANGE_CHARS: &str = "0-9A-Za-z.^~><=*+ |,-";

/// The GBNF grammar llama.cpp is handed.
///
/// Regenerated on every call rather than stored, so there is no copy on disk
/// that can be older than this file.
pub fn gbnf() -> String {
    let operations = ProposedOperation::ALL
        .iter()
        .map(|op| format!("\"\\\"{}\\\"\"", op.name()))
        .collect::<Vec<_>>()
        .join(" | ");

    format!(
        r#"# Generated by thalyx-agent. `thalyx agent grammar` prints this, so the same
# inference can be repeated by hand with --grammar-file and no Thalyx involved.
root       ::= "{{" ws "\"operation\"" ws ":" ws operation ws "," ws "\"targets\"" ws ":" ws targets constraint-field ws "}}"

operation  ::= {operations}

# The empty list is how a model says it did not find one, and it has to be
# expressible or abstention is not a behaviour the model can have. See the note
# in the module docs.
targets    ::= "[" ws (module-id (ws "," ws module-id)*)? ws "]"

# Optional, and absent rather than empty when there is no constraint. A model
# that has nothing to say about the version says nothing about the version.
constraint-field ::= (ws "," ws "\"constraint\"" ws ":" ws constraint)?
constraint ::= "\"" range "\"" | "null"
range      ::= [{RANGE_CHARS}]+

# Reverse-DNS, at least three segments. This mirrors thalyx-manifest, which is
# the authority on what an id is; the grammar's job is to stop tokens being
# spent on things that cannot be one.
module-id  ::= "\"" segment "." segment "." segment ("." segment)* "\""
segment    ::= [{SEGMENT_FIRST}] [{SEGMENT_REST}]*

ws         ::= [ \t\n]*
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::proposal::Proposal;
    use crate::router::looks_like_module_id;

    #[test]
    fn every_operation_the_parser_accepts_appears_in_the_grammar() {
        let grammar = gbnf();
        for operation in ProposedOperation::ALL {
            assert!(
                grammar.contains(operation.name()),
                "the grammar cannot emit {}, so that operation is constrained out \
                 of existence on every tier while the parser still claims to \
                 accept it",
                operation.name()
            );
        }
    }

    #[test]
    fn every_operation_the_grammar_emits_is_one_the_parser_accepts() {
        // The direction that matters more. A grammar naming something the
        // parser refuses makes every inference fail, and a model that fails on
        // everything is indistinguishable from a model that is simply bad at
        // the task — the failure would be blamed on the tier for weeks.
        for operation in ProposedOperation::ALL {
            let emitted = format!(
                r#"{{"operation": "{}", "targets": ["dev.thalyx.demo"]}}"#,
                operation.name()
            );
            assert!(
                Proposal::parse(&emitted).is_ok(),
                "the grammar can emit {emitted}, and the parser refuses it"
            );
        }
    }

    /// Whether a GBNF character-class body such as `a-z0-9_-` admits `c`.
    ///
    /// Reading the class rather than restating it is the whole point: a test
    /// that spelled the same rule a third time would pass while all three
    /// copies were wrong together.
    fn class_admits(body: &str, c: char) -> bool {
        let chars: Vec<char> = body.chars().collect();
        let mut i = 0;
        while i < chars.len() {
            // A `-` with a character on each side is a range; anywhere else it
            // is the literal hyphen, which is why it is written last in the
            // constants above.
            if i + 2 < chars.len() && chars[i + 1] == '-' {
                if (chars[i]..=chars[i + 2]).contains(&c) {
                    return true;
                }
                i += 3;
            } else {
                if chars[i] == c {
                    return true;
                }
                i += 1;
            }
        }
        false
    }

    #[test]
    fn the_grammar_and_the_scanner_agree_on_what_a_module_id_is_made_of() {
        // Two independent statements of the same rule, compared one character
        // at a time by reading the grammar's own character classes. Without
        // this the grammar could permit an id the scanner does not recognise,
        // and the disagreement would only ever surface as a model whose answers
        // get refused for no visible reason.
        for byte in 0x20u8..0x7f {
            let c = byte as char;

            assert_eq!(
                class_admits(SEGMENT_REST, c),
                looks_like_module_id(&format!("a{c}.bb.cc")),
                "{c:?} may appear inside a segment according to only one of the two"
            );

            assert_eq!(
                class_admits(SEGMENT_FIRST, c),
                looks_like_module_id(&format!("{c}a.bb.cc")),
                "{c:?} may start a segment according to only one of the two"
            );
        }
    }

    #[test]
    fn the_class_reader_reads_classes_and_not_something_that_resembles_them() {
        // The instrument includes the harness. A class reader that said yes to
        // everything would make the test above pass while proving nothing.
        assert!(class_admits("a-z0-9_-", 'q'));
        assert!(class_admits("a-z0-9_-", '7'));
        assert!(class_admits("a-z0-9_-", '_'));
        assert!(class_admits("a-z0-9_-", '-'));
        assert!(!class_admits("a-z0-9_-", 'Q'));
        assert!(!class_admits("a-z0-9_-", '.'));
        assert!(!class_admits("a-z", '0'));
    }

    #[test]
    fn a_model_that_found_nothing_has_a_way_to_say_so() {
        // The defect this replaced: a grammar demanding at least one id makes
        // abstention inexpressible, so every ambiguous sentence comes back as a
        // confident invention — and the tier gets blamed for a decision the
        // grammar took away from it.
        assert!(
            gbnf().contains(r#"(module-id (ws "," ws module-id)*)?"#),
            "the target list is not optional, so `I did not find one` cannot be said"
        );

        let abstained = Proposal::parse(r#"{"operation": "install_module", "targets": []}"#)
            .expect("an empty list is a proposal, and a well-formed one");
        assert!(abstained.targets.is_empty());
    }

    #[test]
    fn abstaining_reaches_the_agent_as_nothing_to_do_rather_than_as_an_install() {
        // The other half. An empty list that parsed and then installed the
        // first thing it could find would be the worst of both.
        use crate::transcript::Segment;

        let transcript = crate::Transcript::new().with(Segment::typed("instala algo bueno"));
        struct Abstains;
        impl crate::Model for Abstains {
            fn propose(&self, _: &crate::Transcript) -> Result<String, crate::ModelError> {
                Ok(r#"{"operation": "install_module", "targets": []}"#.to_string())
            }
        }

        let outcome = crate::plan(
            &transcript,
            &Abstains,
            crate::ForeignText::NeverActs,
            thalyx_contract::Caller {
                module_id: "dev.thalyx.agent".to_string(),
                request_id: "req-1".to_string(),
            },
        );
        assert!(matches!(outcome, Err(crate::AgentError::NothingToDo)));
    }

    #[test]
    fn the_grammar_admits_the_line_breaks_a_real_model_actually_used() {
        // Qwen2.5-3B pretty-printed its answer on the first run that reached
        // one: newline, two spaces, one field per line. That is legal only
        // because `ws` contains the newline. Tightening it to `[ \t]*` would
        // make the answer a real model gives unreachable, while every
        // hand-written fixture in this workspace — all of them single-line —
        // carried on passing.
        assert!(
            gbnf().contains(r"ws         ::= [ \t\n]*"),
            "the whitespace rule no longer admits the shape a real model emits"
        );
    }

    #[test]
    fn a_two_segment_id_cannot_be_expressed() {
        // The grammar demands three segments before the optional ones, which is
        // what the scanner demands. Stated as a test because the rule lives in
        // a string literal, where the compiler cannot see it.
        assert!(!looks_like_module_id("thalyx.demo"));
        assert!(gbnf().contains(r#"segment "." segment "." segment ("." segment)*"#));
    }

    #[test]
    fn the_grammar_has_no_field_the_proposal_would_reject() {
        // The mirror of `a_model_that_writes_provenance_is_rejected_rather_than
        // _ignored`: that test proves the parser refuses provenance, this one
        // proves the grammar never offers the model the chance.
        let grammar = gbnf();
        for forbidden in [
            "origins",
            "origin",
            "provenance",
            "confirmed",
            "permissions",
        ] {
            assert!(
                !grammar.contains(forbidden),
                "the grammar mentions {forbidden:?}, which the core decides and \
                 the model is never asked about"
            );
        }
    }

    #[test]
    fn the_grammar_names_the_three_fields_a_proposal_has_and_no_others() {
        let grammar = gbnf();
        for field in ["operation", "targets", "constraint"] {
            assert!(grammar.contains(field), "the grammar omits {field}");
        }
    }
}
