[package]
name = "thalyx-btrfs"
description = "Writing a Btrfs filesystem, without mkfs.btrfs and without libbtrfs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
