/* The kernel types the two BPF programs touch, written by hand.
 *
 * This file used to be generated by `bpftool btf dump file
 * /sys/kernel/btf/vmlinux format c` — 100k lines describing every type in the
 * running kernel, of which these programs use nine. Generating it made three
 * things a requirement of *building* Thalyx: bpftool on the build machine, a
 * kernel compiled with CONFIG_DEBUG_INFO_BTF, and permission to read
 * /sys/kernel/btf/vmlinux.
 *
 * None of the three is needed to *run* anything, and every one of them is a
 * place where somebody else's machine stops. On Ubuntu and its derivatives —
 * which is what a person outside this project is most likely to have — bpftool
 * arrives in `linux-tools-$(uname -r)`, a package published per kernel version,
 * whose name routinely does not match the kernel actually booted. That is a
 * dead end reached after downloading and compiling a kernel, and it has nothing
 * to do with Thalyx.
 *
 * `vault/07-Adopcion-y-Fases/Criterio-de-Salida-Fase-1.md` says Phase 1 ends
 * when a person outside the project boots this, following only the README and
 * with no help. This file is what removes the most fragile thing standing
 * between them and step 1.
 *
 * ## Why the offsets here do not have to be right
 *
 * They are almost certainly wrong, and that is fine — which is the whole reason
 * this is possible at all.
 *
 * `preserve_access_index` makes clang emit a **CO-RE relocation** for every
 * field access instead of a fixed offset: a record saying "the `f_flags` field
 * of `struct file`", by name. The loader looks that name up in the BTF of the
 * kernel it is about to run on and patches the real offset in.
 * `crates/thalyx-bpf/src/core.rs` is what does it, and
 * `vault/09-Notas-Tecnicas/Cargador-BPF-Propio.md` explains why skipping that
 * step produces a program that loads, verifies, runs, and reads the wrong four
 * bytes forever.
 *
 * So what this file has to get right is the **names** — of the structs and of
 * the fields — and the *types* of the fields, since those decide how many bytes
 * are read. What it does not have to get right is where anything sits, how big
 * a struct is, or what else is in it.
 *
 * A field named wrongly here does not read the wrong bytes: the loader fails to
 * find it and refuses to load, which is the cautious answer rule 9 asks for.
 *
 * ## What is deliberately not here
 *
 * Everything else. A struct nothing reads a field of is declared and left
 * empty, because a pointer to it is all the program ever holds.
 */

#ifndef __VMLINUX_H__
#define __VMLINUX_H__

/* The fixed-width types the kernel's headers spell this way. */
typedef unsigned char __u8;
typedef short unsigned int __u16;
typedef unsigned int __u32;
typedef long long unsigned int __u64;
typedef signed char __s8;
typedef short int __s16;
typedef int __s32;
typedef long long int __s64;
typedef _Bool bool;

/* What the generated header emitted for the kernel's own `enum { false, true }`.
 * `<stdbool.h>` is not reachable here: this compiles freestanding for the bpf
 * target, with no libc headers at all. */
enum {
	false = 0,
	true = 1,
};

/* Kernel typedefs that appear in the hook signatures. Their widths matter:
 * they decide how arguments are read out of the trampoline's register save
 * area, and there is no relocation for an argument. */
typedef unsigned short umode_t;
typedef unsigned int dev_t;

/* ── Names that exist only so libbpf's headers can be included ──────────────
 *
 * `bpf_helper_defs.h` declares every BPF helper there is, as function
 * pointers, and the declarations mention types from all over the kernel.
 * Thalyx calls six of those helpers and none of these types, but a
 * declaration still has to typecheck, so the names have to exist.
 *
 * Empty declarations on purpose: nothing here is ever dereferenced, so what
 * they contain is unobservable. Giving them plausible members would be
 * inventing a layout that nothing checks and somebody would later believe.
 *
 * This is the one part of removing the generated header that is genuinely
 * annoying, and it is a straight consequence of libbpf declaring all helpers
 * unconditionally. Each of these is here because the compiler asked for it,
 * one build at a time. */
typedef __u16 __be16;
typedef __u32 __be32;
typedef __u32 __wsum;

struct __sk_buff;
struct bpf_sock;
struct bpf_sock_addr;
struct bpf_sock_ops;
struct bpf_sock_tuple;
struct bpf_perf_event_data;
struct bpf_map;
struct bpf_dynptr;
struct bpf_timer;
struct bpf_spin_lock;
struct bpf_pidns_info;
struct bpf_sysctl;
struct bpf_redir_neigh;
struct bpf_func_info;
struct bpf_sk_lookup;
struct bpf_tcp_sock;
struct bpf_ct_opts;
struct bpf_iter_num;
struct bpf_dynptr_kern;
struct btf_ptr;
struct sk_msg_md;
struct sk_reuseport_md;
struct sk_buff;
struct xdp_md;
struct seq_file;
struct task_struct;
struct linux_binprm;
struct pt_regs;
struct cgroup;
struct sock;
struct tcphdr;
struct tcp_sock;
struct iphdr;
struct ipv6hdr;
struct udp6_sock;
struct unix_sock;
struct mptcp_sock;
struct nf_conn;

/* The map types used by the two programs, by their value in `enum
 * bpf_map_type`. Values, not positions: this is a fragment of an enum rather
 * than the whole one, so counting would be wrong.
 *
 * They are checked against a captured copy of the uapi header —
 * `crates/thalyx-bpf/tests/captured/bpf-uapi-enums.h` — because a constant from
 * another project is captured and not remembered. That rule exists because one
 * of them was written from memory once, was wrong by one, and cost a run on
 * real hardware. */
enum bpf_map_type {
	BPF_MAP_TYPE_UNSPEC = 0,
	BPF_MAP_TYPE_HASH = 1,
	BPF_MAP_TYPE_ARRAY = 2,
	BPF_MAP_TYPE_PERCPU_ARRAY = 6,
	BPF_MAP_TYPE_RINGBUF = 27,
};

/* Everything below is reached by name at load time. The offsets are wrong.
 *
 * `apply_to = record` puts the attribute on every struct declared until the
 * matching pop, so a struct added later cannot quietly miss it — which would
 * compile, load, and read a hard-coded offset from this file against a real
 * kernel. */
#pragma clang attribute push (__attribute__((preserve_access_index)), apply_to = record)

/* enforcement — thalyx_lsm.bpf.c */

struct sockaddr {
	__u16 sa_family;
	char sa_data[14];
};

/* Held only as a pointer: `socket_connect` takes one and the program reads
 * nothing out of it. */
struct socket {
};

/* the watcher — thalyx_watch.bpf.c */

struct super_block {
	dev_t s_dev;
};

struct inode {
	/* Wider than it looks worth being. `i_ino` is `unsigned long`, which is
	 * eight bytes on the targets this builds for, and reading four would
	 * silently truncate every inode number above 4294967295 — on a
	 * filesystem that hands those out, two different files would be
	 * attributed to one. */
	unsigned long i_ino;
};

struct dentry {
	struct inode *d_inode;
	struct dentry *d_parent;
	struct super_block *d_sb;
};

struct path {
	struct dentry *dentry;
};

struct file {
	unsigned int f_flags;
	unsigned int f_mode;
	struct path f_path;
};

/* Pointers only, in the signatures of `inode_setattr`. */
struct iattr {
};

struct mnt_idmap {
};

#pragma clang attribute pop

#endif /* __VMLINUX_H__ */
